### ISSUE TITLE
Node 4 / io.js install trouble

### ISSUE THREAD

**Issue by yeutterg** [hortinstein/node-dash-button#8]
I have a Raspberry Pi running Raspbian Jessie, everything up to date on a fresh install. After installing libpcap and node, and making sure node/npm are up to date (tried all of these: 2.1.0, 4.0.0, 4.1.2), I get an error about the node-gyp rebuild command failing in relation to socketwatcher.

I've looked at the documentation and issues for the dependencies and tried pretty much everything I could find that fixed issues for others. This includes installing a local version of node-gyp instead of the global, using the --unsafe-perm flag, sudo vs. not, messing with nan, etc. All of those did not resolve the issue. 

Here are my [console output](http://pastebin.com/ZncM0gvW) and [npm-debug.log](http://pastebin.com/dxc2VQLh) file.

Any ideas about what to look into next?

**Comment by hortinstein** [comment]
hmmm i have not encountered that before...looks like an issue with node-gyp deps.  Have you tried installing build essential to see if that makes a difference?  

Sorry I am not more help!

**Comment by yeutterg** [comment]
Thanks for the help. Build-essential is definitely installed. I'll take a look at this more deeply and report back if I find a solution.

**Comment by hortinstein** [comment]
heyo...I think I found the problem.  The node-gyp is having issues compiling [node_pcap](https://github.com/mranney/node_pcap) with latest versions of node

https://travis-ci.org/hortinstein/node-dash-button

If you look at the builds, it appears that io.js or the node 2+ series are not working due to compile errors on [node_pcap](https://github.com/mranney/node_pcap).

I will try to update soon.  Opening an issue on the [node_pcap](https://github.com/mranney/node_pcap) repo tomorrow to see  if anyone has workarounds

**Comment by hortinstein** [comment]
Fixed!  It was an issue with compiling an old version of pcap with an outdated dep.  It should work on node 4 now!

**Comment by yeutterg** [comment]
Confirmed that this works! Thanks!

**Comment by hortinstein** [comment]
glad to hear, sorry it took a little while to sort out the issue...thank god for CI
